# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_bridge_pb2 as agent__bridge__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentBridgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Probe = channel.unary_unary(
                '/agentbridge.v1.AgentBridgeService/Probe',
                request_serializer=agent__bridge__pb2.ProbeRequest.SerializeToString,
                response_deserializer=agent__bridge__pb2.ProbeResponse.FromString,
                _registered_method=True)
        self.Ask = channel.unary_unary(
                '/agentbridge.v1.AgentBridgeService/Ask',
                request_serializer=agent__bridge__pb2.AskRequest.SerializeToString,
                response_deserializer=agent__bridge__pb2.AskResponse.FromString,
                _registered_method=True)
        self.PrepareSync = channel.unary_unary(
                '/agentbridge.v1.AgentBridgeService/PrepareSync',
                request_serializer=agent__bridge__pb2.SyncPrepareRequest.SerializeToString,
                response_deserializer=agent__bridge__pb2.SyncPrepareResponse.FromString,
                _registered_method=True)
        self.UploadFileChunk = channel.stream_unary(
                '/agentbridge.v1.AgentBridgeService/UploadFileChunk',
                request_serializer=agent__bridge__pb2.FileChunkUploadRequest.SerializeToString,
                response_deserializer=agent__bridge__pb2.FileChunkUploadResponse.FromString,
                _registered_method=True)
        self.CommitSync = channel.unary_unary(
                '/agentbridge.v1.AgentBridgeService/CommitSync',
                request_serializer=agent__bridge__pb2.SyncCommitRequest.SerializeToString,
                response_deserializer=agent__bridge__pb2.SyncCommitResponse.FromString,
                _registered_method=True)
        self.GetSyncStatus = channel.unary_unary(
                '/agentbridge.v1.AgentBridgeService/GetSyncStatus',
                request_serializer=agent__bridge__pb2.SyncStatusRequest.SerializeToString,
                response_deserializer=agent__bridge__pb2.SyncStatusResponse.FromString,
                _registered_method=True)


class AgentBridgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Probe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFileChunk(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSyncStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentBridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Probe': grpc.unary_unary_rpc_method_handler(
                    servicer.Probe,
                    request_deserializer=agent__bridge__pb2.ProbeRequest.FromString,
                    response_serializer=agent__bridge__pb2.ProbeResponse.SerializeToString,
            ),
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=agent__bridge__pb2.AskRequest.FromString,
                    response_serializer=agent__bridge__pb2.AskResponse.SerializeToString,
            ),
            'PrepareSync': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareSync,
                    request_deserializer=agent__bridge__pb2.SyncPrepareRequest.FromString,
                    response_serializer=agent__bridge__pb2.SyncPrepareResponse.SerializeToString,
            ),
            'UploadFileChunk': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFileChunk,
                    request_deserializer=agent__bridge__pb2.FileChunkUploadRequest.FromString,
                    response_serializer=agent__bridge__pb2.FileChunkUploadResponse.SerializeToString,
            ),
            'CommitSync': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitSync,
                    request_deserializer=agent__bridge__pb2.SyncCommitRequest.FromString,
                    response_serializer=agent__bridge__pb2.SyncCommitResponse.SerializeToString,
            ),
            'GetSyncStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSyncStatus,
                    request_deserializer=agent__bridge__pb2.SyncStatusRequest.FromString,
                    response_serializer=agent__bridge__pb2.SyncStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentbridge.v1.AgentBridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentbridge.v1.AgentBridgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentBridgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Probe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentbridge.v1.AgentBridgeService/Probe',
            agent__bridge__pb2.ProbeRequest.SerializeToString,
            agent__bridge__pb2.ProbeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentbridge.v1.AgentBridgeService/Ask',
            agent__bridge__pb2.AskRequest.SerializeToString,
            agent__bridge__pb2.AskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentbridge.v1.AgentBridgeService/PrepareSync',
            agent__bridge__pb2.SyncPrepareRequest.SerializeToString,
            agent__bridge__pb2.SyncPrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFileChunk(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/agentbridge.v1.AgentBridgeService/UploadFileChunk',
            agent__bridge__pb2.FileChunkUploadRequest.SerializeToString,
            agent__bridge__pb2.FileChunkUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentbridge.v1.AgentBridgeService/CommitSync',
            agent__bridge__pb2.SyncCommitRequest.SerializeToString,
            agent__bridge__pb2.SyncCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSyncStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentbridge.v1.AgentBridgeService/GetSyncStatus',
            agent__bridge__pb2.SyncStatusRequest.SerializeToString,
            agent__bridge__pb2.SyncStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
